### PR TITLE
Add some basic Python packaging

### PR DESCRIPTION
**Pull request by rjw57**
Adds some basic Python packaging and test infrastructure. Please read each commit message carefully since I've tried to describe what each piece does and provide links to more information.

After this PR is merged, anyone should be able to install the software with a single command. (See the README.) In addition travis is set up to automatically test on both Python 3 and Python 2.

Finally, I've included an example port of the fin flutter code and made it a little more "Pythonic". It would be worth having a read through PEP20[1] to get an idea of the "zen" of Python programming.

[1] https://www.python.org/dev/peps/pep-0020/

### CODE REVIEW

**Comment by rjw57** [comment]
I'd like at least three thumbs up for this before merging if possible. Thanks!

**Comment by jb803** [comment]
Looks good :+1:

**Comment by rjw57** [comment]
This provides a nice example of resolving incompatible changes. In this case the README.md file was modified both by this PR and the (now merged) #3.

To fix this I:

```console
$ git checkout master # (in cuspaceflight repo)
$ git pull origin # Update "master" to new version from "origin" (cuspaceflight repo)
$ git checkout python-packaging # Move into the feature branch for this PR
$ git merge master # Shows conflict
$ vim README.md # Fix conflict
$ git add README.md # Tell git
$ git commit # Commit the merge
$ git push rjw57 python-packaging # Push the branch back to GitHub
```
Note that adding a commit to the python-packaging branch automatically added it to this PR. This is why you *never* issue a PR from master. If you do so then every subsequent change also appears in it(!)

**Comment by boyuanxiao** [comment]
:+1: like the ported code.

**Comment by rjw57** [comment]
@boyuanxiao If you're starting to write stuff based on this PR, you should just merge.

**Pull request merged**
